package com.genesis.ginvoice.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.genesis.ginvoice.db.Card;
import com.genesis.ginvoice.db.Invoice;
import com.genesis.ginvoice.db.PersonalInfo;

import com.genesis.ginvoice.db.CardDao;
import com.genesis.ginvoice.db.InvoiceDao;
import com.genesis.ginvoice.db.PersonalInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cardDaoConfig;
    private final DaoConfig invoiceDaoConfig;
    private final DaoConfig personalInfoDaoConfig;

    private final CardDao cardDao;
    private final InvoiceDao invoiceDao;
    private final PersonalInfoDao personalInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cardDaoConfig = daoConfigMap.get(CardDao.class).clone();
        cardDaoConfig.initIdentityScope(type);

        invoiceDaoConfig = daoConfigMap.get(InvoiceDao.class).clone();
        invoiceDaoConfig.initIdentityScope(type);

        personalInfoDaoConfig = daoConfigMap.get(PersonalInfoDao.class).clone();
        personalInfoDaoConfig.initIdentityScope(type);

        cardDao = new CardDao(cardDaoConfig, this);
        invoiceDao = new InvoiceDao(invoiceDaoConfig, this);
        personalInfoDao = new PersonalInfoDao(personalInfoDaoConfig, this);

        registerDao(Card.class, cardDao);
        registerDao(Invoice.class, invoiceDao);
        registerDao(PersonalInfo.class, personalInfoDao);
    }
    
    public void clear() {
        cardDaoConfig.getIdentityScope().clear();
        invoiceDaoConfig.getIdentityScope().clear();
        personalInfoDaoConfig.getIdentityScope().clear();
    }

    public CardDao getCardDao() {
        return cardDao;
    }

    public InvoiceDao getInvoiceDao() {
        return invoiceDao;
    }

    public PersonalInfoDao getPersonalInfoDao() {
        return personalInfoDao;
    }

}
