package com.genesis.ginvoice.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INVOICE".
 */
public class Invoice {

    private Long id;
    private Long card_id;
    private String photo_file_path;
    private String small_photo_path;
    private Float price;
    private String sellerName;
    private String sellerBank;
    private String sellerAddress;
    private String purchaserName;
    private String purchaserAddress;
    private String purchaserRegisterNum;
    private String amountInWords;
    private Float amountInFiguers;
    private String InvoiceNum;
    private String checker;
    private java.util.Date create_time;

    public Invoice() {
    }

    public Invoice(Long id) {
        this.id = id;
    }

    public Invoice(Long id, Long card_id, String photo_file_path, String small_photo_path, Float price, String sellerName, String sellerBank, String sellerAddress, String purchaserName, String purchaserAddress, String purchaserRegisterNum, String amountInWords, Float amountInFiguers, String InvoiceNum, String checker, java.util.Date create_time) {
        this.id = id;
        this.card_id = card_id;
        this.photo_file_path = photo_file_path;
        this.small_photo_path = small_photo_path;
        this.price = price;
        this.sellerName = sellerName;
        this.sellerBank = sellerBank;
        this.sellerAddress = sellerAddress;
        this.purchaserName = purchaserName;
        this.purchaserAddress = purchaserAddress;
        this.purchaserRegisterNum = purchaserRegisterNum;
        this.amountInWords = amountInWords;
        this.amountInFiguers = amountInFiguers;
        this.InvoiceNum = InvoiceNum;
        this.checker = checker;
        this.create_time = create_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCard_id() {
        return card_id;
    }

    public void setCard_id(Long card_id) {
        this.card_id = card_id;
    }

    public String getPhoto_file_path() {
        return photo_file_path;
    }

    public void setPhoto_file_path(String photo_file_path) {
        this.photo_file_path = photo_file_path;
    }

    public String getSmall_photo_path() {
        return small_photo_path;
    }

    public void setSmall_photo_path(String small_photo_path) {
        this.small_photo_path = small_photo_path;
    }

    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    public String getSellerName() {
        return sellerName;
    }

    public void setSellerName(String sellerName) {
        this.sellerName = sellerName;
    }

    public String getSellerBank() {
        return sellerBank;
    }

    public void setSellerBank(String sellerBank) {
        this.sellerBank = sellerBank;
    }

    public String getSellerAddress() {
        return sellerAddress;
    }

    public void setSellerAddress(String sellerAddress) {
        this.sellerAddress = sellerAddress;
    }

    public String getPurchaserName() {
        return purchaserName;
    }

    public void setPurchaserName(String purchaserName) {
        this.purchaserName = purchaserName;
    }

    public String getPurchaserAddress() {
        return purchaserAddress;
    }

    public void setPurchaserAddress(String purchaserAddress) {
        this.purchaserAddress = purchaserAddress;
    }

    public String getPurchaserRegisterNum() {
        return purchaserRegisterNum;
    }

    public void setPurchaserRegisterNum(String purchaserRegisterNum) {
        this.purchaserRegisterNum = purchaserRegisterNum;
    }

    public String getAmountInWords() {
        return amountInWords;
    }

    public void setAmountInWords(String amountInWords) {
        this.amountInWords = amountInWords;
    }

    public Float getAmountInFiguers() {
        return amountInFiguers;
    }

    public void setAmountInFiguers(Float amountInFiguers) {
        this.amountInFiguers = amountInFiguers;
    }

    public String getInvoiceNum() {
        return InvoiceNum;
    }

    public void setInvoiceNum(String InvoiceNum) {
        this.InvoiceNum = InvoiceNum;
    }

    public String getChecker() {
        return checker;
    }

    public void setChecker(String checker) {
        this.checker = checker;
    }

    public java.util.Date getCreate_time() {
        return create_time;
    }

    public void setCreate_time(java.util.Date create_time) {
        this.create_time = create_time;
    }

}
