package com.genesis.ginvoice.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERSONAL_INFO".
 */
public class PersonalInfo {

    private Long id;
    private String name;
    private String company;
    private String phone;
    private String bankId;
    private String bankAddr;
    private String email;

    public PersonalInfo() {
    }

    public PersonalInfo(Long id) {
        this.id = id;
    }

    public PersonalInfo(Long id, String name, String company, String phone, String bankId, String bankAddr, String email) {
        this.id = id;
        this.name = name;
        this.company = company;
        this.phone = phone;
        this.bankId = bankId;
        this.bankAddr = bankAddr;
        this.email = email;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getBankId() {
        return bankId;
    }

    public void setBankId(String bankId) {
        this.bankId = bankId;
    }

    public String getBankAddr() {
        return bankAddr;
    }

    public void setBankAddr(String bankAddr) {
        this.bankAddr = bankAddr;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

}
